/// <reference types="expo/types" />

// NOTE: This file should not be edited. It is auto-generated by Expo CLI
// and enables typed routes for expo-router. If you see missing types,
// run `npx expo customize expo-env.d.ts` or start the dev server once.
